const grid = document.querySelector('#project-grid');
const dialog = document.querySelector('#project-dialog');
const content = document.querySelector('#dialog-content');
const url = path => path.split('/').map(encodeURIComponent).join('/');
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let opener;
const imageOrType = p => p.cover ? `<img loading="lazy" src="${url(p.cover)}" alt="${esc(p.title)}作品局部预览">` : `<span class="cover-type">${esc(p.graphic||p.title)}</span>`;
const card = p => `<button class="project-card" data-id="${p.id}" aria-label="查看：${esc(p.title)}"><div class="project-cover ${p.tone} ${p.coverStyle||''}${p.mediaType==='video'?' video-cover':''}"><span class="cover-index">${(p.files[0]?.[1] || '').endsWith('.mp4')?'VIDEO':(p.files[0]?.[1] || '').endsWith('.pdf')?'PDF':p.mediaType==='article'?'公众号原文':p.mediaType==='text'?'项目介绍':'图文作品'}</span>${imageOrType(p)}${p.durationLabel?`<span class="video-duration">${p.durationLabel}</span>`:''}<span class="cover-arrow" aria-hidden="true">${p.files.some(([,f])=>/\.mp4$/i.test(f))?'▷':'↗'}</span></div><div class="card-body">${p.role?`<span class="role-tag">${esc(p.role)}</span>`:''}<h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p>${p.disclosure?`<p class="project-disclosure">${esc(p.disclosure)}</p>`:''}<span class="card-action">${p.files.some(([,f])=>/\.mp4$/i.test(f))?'播放这支作品':p.originalUrl?'阅读公众号原文':p.mediaType==='text'?'阅读项目介绍':p.mediaType==='video'?'查看作品介绍':'查看完整作品'} ↗</span></div></button>`;
const groups = c => {const ps=projects.filter(p=>p.category===c.id);return [...new Set(ps.map(p=>p.group||''))].map(group=>`<div class="work-subgroup">${group?`<h4 class="subgroup-title">${esc(group)} <span>${ps.filter(p=>(p.group||'')===group).length} 件</span></h4>`:''}<div class="project-grid">${ps.filter(p=>(p.group||'')===group).map(card).join('')}</div></div>`).join('');};
grid.innerHTML=categories.map((c,i)=>`<section class="work-section" id="works-${c.id}" data-category="${c.id}"><div class="category-heading"><div><div class="eyebrow">${String(i+1).padStart(2,'0')} / ${c.en}</div><h3>${c.name}<span>${projects.filter(p=>p.category===c.id).length} 件</span></h3><p>${c.intro}</p></div><span class="category-note">${c.note}</span></div>${groups(c)}</section>`).join('');
document.querySelector('.filters').innerHTML='<button class="active" data-filter="all" aria-pressed="true">全部类型</button>'+categories.map(c=>`<button data-filter="${c.id}" aria-pressed="false">${c.name}</button>`).join('');
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});document.querySelectorAll('.work-section').forEach(section=>section.hidden=button.dataset.filter!=='all'&&section.dataset.category!==button.dataset.filter);}));
grid.addEventListener('click',event=>{
 const trigger=event.target.closest('[data-id]');if(!trigger)return;opener=trigger;
 const p=projects.find(p=>p.id===trigger.dataset.id), c=categories.find(c=>c.id===p.category);
 if(p.mediaType==='article'&&/^https:\/\//i.test(p.originalUrl||'')){window.open(p.originalUrl,'_blank','noopener,noreferrer');return;}
 content.innerHTML=`<div class="eyebrow">${c.name}${p.group?' / '+p.group:''}</div><h2 id="dialog-title">${esc(p.title)}</h2>${p.role?`<p class="detail-meta">我的职责 / ${esc(p.role)}</p>`:''}<p class="detail-copy">${esc(p.description)}</p>${p.facts.length?`<dl class="detail-copy">${p.facts.map(([label,value])=>`<dt>${esc(label)}</dt><dd>${esc(value)}</dd>`).join('')}</dl>`:''}${p.disclosure?`<p class="project-disclosure">${esc(p.disclosure)}</p>`:''}<div class="file-links">${p.originalUrl&&/^https:\/\//i.test(p.originalUrl)?`<a class="original-link" href="${esc(p.originalUrl)}" target="_blank" rel="noopener noreferrer">阅读原文 ↗</a>`:''}${p.files.map(([name,path])=>`<a href="${url(path)}" target="_blank" rel="noopener">${esc(name)} ↗</a>`).join('')}</div>`;
 const file=(p.files[0]?.[1] || '');
 if(/\.mp4$/i.test(file))content.insertAdjacentHTML('beforeend',`<video controls playsinline preload="none" ${p.cover?`poster="${url(p.cover)}"`:''} src="${url(file)}">请通过上方链接打开视频。</video><p class="detail-meta">若浏览器无法播放，可通过上方链接使用本地播放器观看。</p>`);
 else if(/\.(png|jpg)$/i.test(file))content.insertAdjacentHTML('beforeend',`<img class="full-image" src="${url(file)}" alt="${esc(p.title)}完整作品">`);
 else if(/\.pdf$/i.test(file))content.insertAdjacentHTML('beforeend',`<object class="pdf-preview" data="${url(file)}" type="application/pdf"><p>请点击上方链接阅读完整 PDF。</p></object>`);
 dialog.showModal();dialog.scrollTop=0;document.body.style.overflow='hidden';
});
document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
dialog.addEventListener('close',()=>{content.querySelectorAll('video').forEach(v=>{v.pause();v.removeAttribute('src');v.load();});content.innerHTML='';document.body.style.overflow='';opener?.focus();});
const printPages=[];
for(const c of categories){const ps=projects.filter(p=>p.category===c.id);for(let i=0;i<ps.length;i+=2)printPages.push({c,ps:ps.slice(i,i+2),continued:i>0});}
const total=printPages.length+1;
const foot=n=>`<div class="print-foot">郭湘妮 · 作品集 / 3381613703@qq.com <span style="float:right">${n} / ${total}</span></div>`;
const printCard=p=>`<article class="print-project${p.mediaType==='video'?' print-video':''}${p.mediaType==='text'?' print-text-project':''}">${p.mediaType==='text'?'':p.cover?`<img src="${url(p.cover)}" alt="${esc(p.title)}预览">`:`<div class="print-graphic">${esc(p.graphic||p.title)}</div>`}<div><p class="print-category">${esc(p.group||categories.find(c=>c.id===p.category).name)}</p><h3>${esc(p.title)}</h3>${p.role?`<p><b>我的职责：</b>${esc(p.role)}</p>`:''}<p>${esc(p.description)}</p>${p.facts.map(([k,v])=>`<p><b>${esc(k)}：</b>${esc(v)}</p>`).join('')}<p class="print-media-note">${/\.mp4$/i.test((p.files[0]?.[1] || ''))?'视频作品 · 网页版可播放':/\.pdf$/i.test((p.files[0]?.[1] || ''))?'完整 PDF · 网页版可阅读':p.originalUrl?`<a href="${esc(p.originalUrl)}">阅读公众号原文 ↗</a>`:p.mediaType==='text'?esc(p.disclosure||'项目经历 · 仅提供文字介绍'):p.mediaType==='video'?'视频作品 · 公开版仅展示封面与介绍':'本页展示原作局部 · 网页版可查看完整长图'}</p></div></article>`;
document.querySelector('#print-portfolio').innerHTML=`<section class="print-page"><div class="print-kicker">GUO XIANGNI / PORTFOLIO</div><h1>郭湘妮<br>作品集</h1><p>南京师范大学 · 新闻学（全媒体运营方向）<br>2023.09 — 2027.06 · 本科在读</p><p>项目探索 / AI 实践 / 创作记录</p><div class="print-intro"><h2>${categories.length} 类作品，${projects.length} 件实践</h2>${categories.map(c=>`<p><b>${c.name}</b> / ${projects.filter(p=>p.category===c.id).length} 件<br>${c.note}</p>`).join('')}</div><p>邮箱：3381613703@qq.com<br>电话：15673335126</p><p class="print-media-note">按类型收录项目与作品，完整公开作品可在网页版查看。<br>悦境母语仅提供文字介绍，不包含未公开素材。</p>${foot(1)}</section>`+printPages.map(({c,ps,continued},i)=>`<section class="print-page"><div class="print-kicker">${c.en} / ${c.name}${continued?'（续）':''}</div><h2>${c.name}</h2>${ps.map(printCard).join('')}${foot(i+2)}</section>`).join('');
document.querySelectorAll('.print-button').forEach(b=>b.addEventListener('click',()=>window.print()));
